[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
decorations = "Full"
title = "Quinn's Terminal"
dynamic_title = false
dynamic_padding = true
