# A lot of this comes from https://theari.dev/blog/enhanced-helix-config/
theme = "quinn-theme"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor]
mouse = false
color-modes = true
cursorline = true
bufferline = "always"
popup-border = "popup"
rulers = [80]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
auto-signature-help = false

[editor.statusline]
left = ["mode", "spinner", "spacer", "read-only-indicator", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "register", "file-type", "file-encoding", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

